-- FIRST_HALF와 ICECREAM_INFO를 JOIN
-- INGREDIENT_TYPE 기준으로 GROUP BY
-- SUM으로 총 주문량 계산 후 내림차순 정렬

SELECT I.INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF F, ICECREAM_INFO I
WHERE F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;
