-- 1. BOOK과 AUTHOR 테이블을 AUTHOR_ID 기준으로 JOIN
-- 2. CATEGORY가 '경제'인 데이터 필터링
-- 3. DATE_FORMAT을 사용하여 날짜 형식 변환
-- 4. 출판일 기준으로 정렬

SELECT 
    B.BOOK_ID, 
    A.AUTHOR_NAME, 
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B 
INNER JOIN AUTHOR A 
    ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE;
